augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    avg_pool: true
    is_flatten: true
    keep_prob: 0.0
  name: resnet12
batch_size: 128
classifier:
  kwargs:
    feat_dim: 640
    ifsl_param:
      approx: false
      class_num: 351
      cls_path: /data1/student/hxh/ssl/results/IfslPretrain-tiered_imagenet-resnet12-5-1-Aug-15-2024-11-29-15/checkpoints/classifier_best.pth
      d_feature: ed
      feature_path: /data1/student/hxh/ssl/pretrained/lsq-resnet.npy
      fusion: concat
      is_cosine_feature: true
      logit_fusion: product
      n_splits: 16
      normalize_before_center: false
      normalize_d: false
      normalize_ed: false
      preprocess_after_split: none
      preprocess_before_split: none
      single: true
      sum_log: false
      temp: 100
      use_counterfactual: false
      use_x_only: false
      x_zero: false
    inner_param:
      lr: 0.01
      test_iter: 20
      train_iter: 20
  name: DMatchingNet
data_root: /data1/student/hxh/tiered_imagenet
dataloader_num: 1
deterministic: true
device_ids: 1,2
episode_size: 2
epoch: 100
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 20
  name: StepLR
n_gpu: 2
optimizer:
  kwargs:
    lr: 0.0001
  name: Adam
  other: null
parallel_part:
- emb_func
port: 31725
pretrain_path: /data1/student/hxh/ssl/results/IfslPretrain-tiered_imagenet-resnet12-5-1-Aug-15-2024-11-29-15/checkpoints/emb_func_best.pth
query_num: 15
rank: 0
result_root: ./results
resume: false
save_interval: 10
save_part:
- emb_func
seed: 2147483647
shot_num: 5
tag: null
tb_scale: 1.6666666666666667
test_episode: 600
test_epoch: 5
test_query: 15
test_shot: 5
test_way: 5
train_episode: 1000
use_memory: false
val_per_epoch: 1
warmup: 0
way_num: 5
workers: 8
